//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNIKSERVIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATURABILGI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FATURABILGI()
        {
            this.FATURADETAYs = new HashSet<FATURADETAY>();
        }
    
        public int ID { get; set; }
        public string SERI { get; set; }
        public string SIRANO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SAAT { get; set; }
        public string VERGIDAIRE { get; set; }
        public Nullable<int> CARIID { get; set; }
        public Nullable<int> PERSONELID { get; set; }
    
        public virtual CARI CARI { get; set; }
        public virtual PERSONEL PERSONEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATURADETAY> FATURADETAYs { get; set; }
    }
}
