//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNIKSERVIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicariTeknikServisEntities : DbContext
    {
        public TicariTeknikServisEntities()
            : base("name=TicariTeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<ARIZADETAY> ARIZADETAYs { get; set; }
        public virtual DbSet<CARI> CARIs { get; set; }
        public virtual DbSet<DEPARTMAN> DEPARTMen { get; set; }
        public virtual DbSet<FATURABILGI> FATURABILGIs { get; set; }
        public virtual DbSet<FATURADETAY> FATURADETAYs { get; set; }
        public virtual DbSet<KATEGORI> KATEGORIs { get; set; }
        public virtual DbSet<NOTLARIM> NOTLARIMs { get; set; }
        public virtual DbSet<PERSONEL> PERSONELs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<URUN> URUNs { get; set; }
        public virtual DbSet<URUNHAREKET> URUNHAREKETs { get; set; }
        public virtual DbSet<URUNKABUL> URUNKABULs { get; set; }
        public virtual DbSet<URUNTAKIP> URUNTAKIPs { get; set; }
    }
}
