//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNIKSERVIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNHAREKET
    {
        public int HAREKETID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> MUSTERIID { get; set; }
        public Nullable<int> PERSONELID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<short> ADET { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        public virtual CARI CARI { get; set; }
        public virtual PERSONEL PERSONEL { get; set; }
        public virtual URUN URUN { get; set; }
    }
}
