//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNIKSERVIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNTAKIP
    {
        public int ID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public string DURUM { get; set; }
        public Nullable<int> TARIH { get; set; }
        public string TAKIPKODU { get; set; }
    
        public virtual URUN URUN { get; set; }
    }
}
