//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKNIKSERVIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNKABUL
    {
        public int ISLEMID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> CARIID { get; set; }
        public Nullable<int> PERSONELID { get; set; }
        public Nullable<System.DateTime> GELISTARIH { get; set; }
        public Nullable<System.DateTime> CIKISTARIH { get; set; }
    
        public virtual CARI CARI { get; set; }
        public virtual PERSONEL PERSONEL { get; set; }
        public virtual URUN URUN { get; set; }
    }
}
